@startuml sequenceEj-1
!define BlueGreen [color=blue]
!define GreenBlue [color=green]

skinparam SequenceMessageAlignment center
skinparam participant {
  backgroundColor<<BlueGreen>> GreenBlue
}

title Roaming de Voz - Documentación de Diseño

participant "main.py" as M
participant "elastic_services.py" as E
participant "temip_services.py" as T
participant "teams_searvices.py" as TT

activate M
M -[#Blue]-> E: getElasticpipTpsUsageData()
activate E
E -[#Green]-> M: stpElasticData
M -> M: handleElasticSTPTpsUsageData()
deactivate E

M -[#Blue]-> E: getElasticSuccessRate()
activate E
E -[#Green]-> M: stpSuccessRate
M -> M: handleElasticSTPTpsUsageData()
deactivate E

M -[#DarkRed]-> TT: sendProblemToTeams(data)
activate TT

M -[#Blue]-> T: getSTPTemipAlarms()
activate T
T -[#Green]-> M: stpTemipAlarms
deactivate T

M -> M: handleSTPTemipAlarms()
deactivate TT

@enduml
