@startuml sequenceEj-2
!define BlueGreen [color=blue]
!define GreenBlue [color=green]

skinparam SequenceMessageAlignment center
skinparam participant {
  backgroundColor<<BlueGreen>> GreenBlue
}

title Roaming de Voz - Documentación de Diseño

participant "main.py" as M
participant "elastic_services.py" as E
participant "temip_services.py" as T
participant "teams_searvices.py" as TT

activate M
M -[#Blue]-> E: getElasticStpIpTpsUsageData()
activate E
E -[#Green]-> M: stpElasticData
deactivate E
M -> M: handleElasticSTPTpsUsageData()


M -[#DarkRed]-> TT: sendProblemToTeams(data)


M -[#Blue]-> E: getElasticSuccessRate()
activate E
E -[#Green]-> M: stpSuccessRate
deactivate E
M -> M: handleElasticSTPTpsUsageData()
M -[#DarkRed]-> TT: sendProblemToTeams(data)


M -[#Blue]-> T: getSTPTemipAlarms()
activate T
T -[#Green]-> M: stpTemipAlarms
deactivate T

M -> M: handleSTPTemipAlarms()

M -[#DarkRed]-> TT: sendProblemToTeams(data)

deactivate M
deactivate TT
@enduml
