@startuml cu-01
left to right direction
skinparam packageStyle rect
actor Cliente as customer
actor Cajero as cashier
rectangle "Máquina Expendedora de Refrescos" {
  customer -- (Seleccionar Refresco)
  (Seleccionar Refresco) .> (Realizar Pago) : include
  (Devolver Cambio) -- (Realizar Pago) : extend
  (Solicitar Ayuda) .> (Seleccionar Refresco) : extends
  (Seleccionar Refresco) -- cashier
}
@enduml

