@startuml SeriePort

!define AMARILLO #F3C328

skinparam backgroundColor transparent
skinparam activityBackgroundColor AMARILLO
skinparam activityBorderColor AMARILLO
skinparam activityFontColor Black
skinparam loopBackgroundColor AMARILLO
skinparam loopBorderColor AMARILLO
skinparam loopFontColor Black

title Ejemplo 2

start
if (condition A) then (yes)
  :Texto 1;
elseif (condition B) then (yes)
  :Texto 2;
  stop
(no) elseif (condition C) then (yes)
  :Texto 3;
(no) elseif (condition D) then (yes)
  :Texto 4;
else (nothing)
  :Texto else;
endif

stop

@enduml




