@startuml SeriePort

!define AMARILLO #F3C328

skinparam backgroundColor transparent
skinparam activityBackgroundColor AMARILLO
skinparam activityBorderColor AMARILLO
skinparam activityFontColor Black
skinparam loopBackgroundColor AMARILLO
skinparam loopBorderColor AMARILLO
skinparam loopFontColor Black

title Ejemplo 2

start


stop

@enduml




